apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft-server-prod

resources:
  - namespace.yaml
  - storageclass.yaml
  - configmap-server-properties.yaml
  - pvc.yaml
  - service-headless.yaml
  - service-game.yaml
  - service-rcon.yaml
  - networkpolicy.yaml
  - statefulset.yaml
  - poddisruptionbudget.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: minecraft-server
      app.kubernetes.io/managed-by: kustomize
