apiVersion: v1
kind: LimitRange
metadata:
  name: mc-server-limits
  namespace: minecraft-server-prod
  labels:
    app.kubernetes.io/name: mc-server
    app.kubernetes.io/component: servidor-jogo
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 1Gi
      default:
        cpu: "1"
        memory: 1536Mi
      max:
        cpu: "2"
        memory: 3Gi
      min:
        cpu: 100m
        memory: 256Mi
    - type: PersistentVolumeClaim
      max:
        storage: 32Gi
      min:
        storage: 1Gi
