apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mc-server-pdb
  namespace: minecraft-server-prod
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: mc-server
