apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mc-server-pdb
  namespace: minecraft-server-prod
  labels:
    app.kubernetes.io/name: mc-server
    app.kubernetes.io/component: servidor-jogo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mc-server
