apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data
  namespace: minecraft-server-prod
  labels:
    app.kubernetes.io/name: mc-server
    app.kubernetes.io/component: armazenamento
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mc-standard-ssd
  resources:
    requests:
      storage: 32Gi
