apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data
  namespace: minecraft-server-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mc-standard-ssd
  resources:
    requests:
      storage: 32Gi
