apiVersion: v1
kind: Service
metadata:
  name: mc-server-rcon
  namespace: mc-prod
  labels:
    app.kubernetes.io/name: mc-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mc-server
  ports:
    - name: rcon
      port: 25575
      targetPort: 25575
      protocol: TCP
