apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-world-backup
  namespace: minecraft-server-prod
  labels:
    app.kubernetes.io/name: mc-world-backup
    app.kubernetes.io/component: backup-mundo
  annotations:
    azure.workload.identity/client-id: BACKUP_AZURE_CLIENT_ID_PLACEHOLDER
