name: CI Validate Terraform
description: tflint, tfsec e terraform validate

runs:
  using: composite

  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.8"

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.54.0

    - name: TFLint init
      shell: bash
      run: tflint --init --config=$(pwd)/linters/.tflint.hcl

    - name: TFLint
      shell: bash
      run: |
        CONFIG="$(pwd)/linters/.tflint.hcl"
        for dir in infra/terraform/live/prod; do
          echo ">>> tflint ${dir}"
          (cd "${dir}" && tflint --config="${CONFIG}" --minimum-failure-severity=error)
        done

    - name: Instalar tfsec
      shell: bash
      run: |
        curl -fsSL -o /tmp/tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.11/tfsec-linux-amd64
        chmod +x /tmp/tfsec
        sudo mv /tmp/tfsec /usr/local/bin/tfsec
        tfsec --version

    - name: tfsec
      shell: bash
      run: tfsec --config-file linters/.tfsec.yml .

    - name: Terraform validate live prod
      shell: bash
      run: |
        cd infra/terraform/live/prod
        terraform init -backend=false
        terraform validate
