apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: acrminecraftserverprod.azurecr.io/minecraft-core-server
    newName: acrminecraftserverprod.azurecr.io/minecraft-core-server
    newTag: placeholder

patches:
  - path: patches/resources.yaml
  - path: patches/networkpolicy-cidrs.yaml
